name: Deploy Lambda Functions

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Zip and Upload Lambdas
      uses: appleboy/lambda-action@v1.0.0
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ca-central-1
        function_name: ${{ matrix.function }}
        zip_file: lambda/${{ matrix.function }}/
      strategy:
        matrix:
          function:
            - get_all_inventory_items
            - get_inventory_item
            - add_inventory_item
            - delete_inventory_item
            - get_location_inventory_items
